SELECT distinct

	EXTRACT( YEAR FROM ccorrente.DTPREVISTA ) ||'/'|| lpad( EXTRACT( MONTH FROM ccorrente.DTPREVISTA ),2,'0') AS MES_ANO,
	EXTRACT( YEAR FROM ccorrente.DTPREVISTA ) AS ANO,       lpad( EXTRACT( MONTH FROM ccorrente.DTPREVISTA ),2,'0') AS MES

FROM ccorrente

WHERE CCORRENTE.DTPREVISTA >= cast('01.01.2021' as date)
	--AND CCORRENTE.DTPREVISTA <= current_date

union

SELECT distinct

EXTRACT( YEAR FROM ICP.DTVENCTO ) ||'/'|| lpad( EXTRACT( MONTH FROM ICP.DTVENCTO ),2,'0') AS MES_ANO,
EXTRACT( YEAR FROM ICP.DTVENCTO ) AS ANO,       lpad( EXTRACT( MONTH FROM ICP.DTVENCTO ),2,'0') AS MES FROM ICP

WHERE 1=1
AND ICP.DTVENCTO >= cast('01.01.2021' as date)
--AND ICP.DTVENCTO <= current_date
order by 1