WITH BANCO_CONTA AS(
	SELECT DISTINCT
	BANCO.NOMEBANCO,
	CCORRENTE_SALDO.BANCO,
	CCORRENTE_SALDO.CONTA,
	MAX( CCORRENTE_SALDO.DATA ) AS DATA

	FROM CCORRENTE_SALDO
	INNER JOIN BANCO ON BANCO.BANCO = CCORRENTE_SALDO.BANCO
	INNER JOIN CONTA ON CONTA.BANCO = CCORRENTE_SALDO.BANCO
			AND CONTA.CONTA = CCORRENTE_SALDO.CONTA
	WHERE CCORRENTE_SALDO.TIPO = 1
			AND CCORRENTE_SALDO.DATA >= '01.01.2021'
			AND CCORRENTE_SALDO.DATA <= current_date
			and CCORRENTE_SALDO.CONTA <> '04912-3'

	GROUP BY
		BANCO.NOMEBANCO,
		CCORRENTE_SALDO.BANCO,
		CCORRENTE_SALDO.CONTA)

	SELECT

		BANCO_CONTA.NOMEBANCO,
		CCORRENTE_SALDO.BANCO,
		CCORRENTE_SALDO.CONTA,
		BANCO_CONTA.DATA,
		CCORRENTE_SALDO.vrlancto

	FROM BANCO_CONTA

	INNER JOIN CCORRENTE_SALDO ON CCORRENTE_SALDO.BANCO = BANCO_CONTA.BANCO
		AND CCORRENTE_SALDO.conta = BANCO_CONTA.CONTA
		AND CCORRENTE_SALDO.data  = BANCO_CONTA.DATA
		AND CCORRENTE_SALDO.tipo = 1

	WHERE ccorrente_saldo.banco <> 999