SELECT DISTINCT
    CONFIG.CODIGO,
    CONFIG.RAZSOCIALDESCRIPTOGRAFADO AS RAZSOCIAL ,
    CCUSTO.DESPESA AS GRUPO,
    GRUPODESP.DESCGRUPO,
    CCUSTO.DESCRCCUSTO AS NOME_DESPESA,
    CCORRENTE.HISTORICO,
    case
        when ccusto.TIPODESPESA = 1 then
            'DESPESAS FIXAS'
        when ccusto.TIPODESPESA = 2 then
            'DESPESAS VARIÁVEIS'
        when ccusto.TIPODESPESA = 7 then
            'DESPESAS FINANCEIRAS'
        when ccusto.TIPODESPESA = 3 then
            'DEPRECIAÇÃO'
        when ccusto.TIPODESPESA = 4 then
            'INVESTIMENTOS'
        when ccusto.TIPODESPESA = 5 then
            'EMPRÉSTIMOS'
        when ccusto.TIPODESPESA = 6 then
            'RETIRADA/DIVIDENDOS'
        when ccusto.TIPODESPESA = 8 then
            'IMPOSTOS SOBRE VENDA'
        when ccusto.TIPODESPESA = 9 then
            'IMPOSTOS SOB LUCRO CONTÁBIL'
    end as TIPO_DESPESA,
    FORNEC.RAZSOCIAL AS FORNECEDOR,
    EXTRACT( YEAR FROM CCORRENTE.DTPREVISTA )||'/'||lpad( EXTRACT( MONTH FROM CCORRENTE.DTPREVISTA ),2,'0') AS MES_ANO,
    EXTRACT( YEAR FROM CCORRENTE.DTCOMPETENCIA )||'/'||lpad( EXTRACT( MONTH FROM CCORRENTE.DTCOMPETENCIA ),2,'0') AS MES_ANO_COMPET,
    --lpad(ccorrente.NRLANCTO, 9, '0') nrlancto,
    ccorrente.PARCELA,
    ccorrente.DTCOMPETENCIA data_emissao,
    lpad(ccorrente.documento, 9, '0') nrdocumento,
    ccorrente.DTEFETIVA  AS data_efetiva,
    CAST(SUM(VRLANCTO*(-1))AS NUMERIC(15,2))AS VRTOTAL

FROM CCORRENTE
INNER JOIN CCUSTO ON CCUSTO.CCUSTO = CCORRENTE.DESPESA
INNER JOIN SERIE ON SERIE.SERIE = CCORRENTE.SERIE
INNER JOIN CONFIG ON CONFIG.CODIGO = SERIE.EMPRESA
LEFT OUTER JOIN GRUPODESP ON CCUSTO.DESPESA = GRUPODESP.GRUPODESP
LEFT OUTER JOIN FORNEC ON FORNEC.CODIGO = CCORRENTE.FORNECEDOR
WHERE 1=1
AND CCORRENTE.DESPESA > 0
AND CCORRENTE.DTPREVISTA >= cast('01.01.2021' as date)
AND CCORRENTE.DTPREVISTA <= current_date
AND CCUSTO.ECONOMICO <> 'T'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14