SELECT DISTINCT
        LPAD(C.NRPEDIDO, 9, '0') AS PEDIDO,
        --'' as SERIE,
        --'' as NRNFCF,
        C.DTPEDIDO AS DATA,
        --cte_condpagto.DTPAGTO AS DTPAGTO,
        --cte_condpagto.FORMAPAGTO AS FORMA_PAGAMENTO,
        --cte_condpagto.PARCELA AS PARCELA_CPP,
        I.CFOP AS NATOPERACAO,
        C.CLIENTE,
        C.RAZSOCIAL,
        'BRASIL' AS PAISFAT,
        CASE WHEN COALESCE(C.CIDADEFAT, '') <> '' THEN C.CIDADEFAT
        ELSE CLIFOR.CIDADEFAT END AS CIDADEFAT,
        CASE WHEN COALESCE(C.UFFAT, '') <> '' THEN C.UFFAT
        ELSE CLIFOR.UFFAT END AS UFFAT,
        CLIFOR.DTCAD,
        '' AS AUTORIZADO,
        C.VENDEDOR,
        '' AS MOTIVODEVOLUCAO,
        C.TRANSPORTADORA,
        C.MOTIVOBLOQ,
        C.USUARIOLIBERACAO,
        '' AS FINANCEIRO,
        T.CONTROLEESTOQUE AS ENTSAI,
        I.ALIQICMS,
        N.NATUREZA,
        ATEND.DESCRICAO AS NATENDIMENTO, 
        F.NOME AS NVENDEDOR,
        COALESCE(IND.NOME, 'SEM INDICAÇÃO') AS NINDICACAO,
        CLIFOR.CONVENIO_FUNC,
        COALESCE(T.DESCRICAO, 'EM BRANCO') AS NTIPOPED,
        
        CASE
           WHEN (CONFIG2.UTILIZACONTROLEENTREGA <> 'T') THEN
              C.DTFATURA
        END AS DT_ENTREGA,
        
        I.TRIBUTACAO,
        I.VRFRETE AS VRTOTFRETE,
        MAX( RAMOATIV.DESCRRAMO ) AS DESCRRAMO,
        MAX( CONVENIO.DESCRCONVENIO ) AS DESCRCONVENIO,
        MAX( CLIGRUPO.DESCRGRUPO ) AS DESCRGRUPO,
        MAX( TP1.RAZSOCIAL ) AS NTRANSPORTADORA,
        MAX( TP2.RAZSOCIAL ) AS NREDESPACHO,

        SUM(
         CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
              (COALESCE(I.VRUNITARIO * I.QTDE,0) -
               COALESCE(I.DESCONTO,0) -
               COALESCE(I.DESCTOTAL,0) +
               COALESCE(I.ACRESCIMO,0)) * (-1)
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
              (COALESCE(I.VRUNITARIO * I.QTDE,0) -
               COALESCE(I.DESCONTO,0) -
               COALESCE(I.DESCTOTAL,0) +
               COALESCE(I.ACRESCIMO,0))
         ELSE 0
        END) AS VRVENDAFORMACAO,

        SUM(
            CASE  WHEN (COALESCE(CTAB.FP_CONSIDERAFRETE, 'F') = 'T') AND (C.FRETECONTA_T = 1) THEN
            (COALESCE(I.VRUNITARIO * I.QTDE,0) +
             COALESCE(I.BASEICMSFRETE,0) +
            (COALESCE(I.VRIPI, 0) +COALESCE(I.VRIPIACRESCIMO, 0)) +
             COALESCE(I.ACRESCIMO,0)-
             (COALESCE(I.DESCONTO,0) +
              COALESCE(I.DESCTOTAL,0)))
          ELSE
          (COALESCE(I.VRUNITARIO * I.QTDE,0) +
            (COALESCE(I.VRIPI, 0) +COALESCE(I.VRIPIACRESCIMO, 0)) +
             COALESCE(I.ACRESCIMO,0)-
             (COALESCE(I.DESCONTO,0) +
              COALESCE(I.DESCTOTAL,0)))
       END )     AS VRTOTITEMLIQ,


        SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') THEN
             COALESCE(I.VRUNITARIO * I.QTDE,0) *(-1)
           WHEN (T.CONTROLEESTOQUE = 'S') THEN
              COALESCE(I.VRUNITARIO * I.QTDE,0)
           ELSE
              (COALESCE(I.VRUNITARIO * I.QTDE,0))
        END) AS VRTOTITEM,

        CAST(SUM(
           CASE
              WHEN (N.VISTAPRAZO = 'S') AND (T.CONTROLEESTOQUE = 'E') THEN
                 COALESCE(I.COMISSAO,0) * (-1)
              WHEN (N.VISTAPRAZO = 'S') AND (T.CONTROLEESTOQUE <> 'E' ) THEN
                 COALESCE(I.COMISSAO,0)
              ELSE 
                 0.00
            END ) AS NUMERIC(15, 4)) AS COMISSAO,

        CAST(SUM (cast(I.vrcomissao_i as numeric(15,2))) AS NUMERIC(18,2)) as COMISSAOIND,


        SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') THEN
                (COALESCE(I.CUSTO,0)*(COALESCE(I.QTDE,0)))*(-1)
           ELSE (COALESCE(I.CUSTO,0)*(COALESCE(I.QTDE,0)))
        END)
            AS CUSTOLIQ,

        SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') THEN
             (COALESCE(I.VRUNITARIO * I.QTDE,0) - COALESCE(I.BASEICMSFRETE,0) -  COALESCE(I.DESCONTO,0) - COALESCE(I.DESCTOTAL,0) +
              COALESCE(I.ACRESCIMO,0))*(-1)
           WHEN (T.CONTROLEESTOQUE = 'S') THEN
              COALESCE(I.VRUNITARIO * I.QTDE,0) - COALESCE(I.BASEICMSFRETE,0) -  COALESCE(I.DESCONTO,0) - COALESCE(I.DESCTOTAL,0) +
              COALESCE(I.ACRESCIMO,0)
           ELSE 0
        END) AS VRLIQ,

       SUM(
        CASE
           WHEN (N.FINANCEIRO = 'S') AND (N.TIPONF = 'E') THEN
              (COALESCE(I.VRUNITARIO * I.QTDE,0) -
               COALESCE(I.DESCONTO,0) -
               COALESCE(I.DESCTOTAL,0) +
               COALESCE(I.VRSUBSTICMS, 0) +
               (COALESCE(I.VRIPIACRESCIMO, 0)+COALESCE(I.VRIPI, 0)) +
               COALESCE(I.ACRESCIMO,0)) * (-1)
           WHEN (N.FINANCEIRO = 'S') AND (N.TIPONF = 'S') THEN
              (COALESCE(I.VRUNITARIO * I.QTDE,0) -
               COALESCE(I.DESCONTO,0) -
               COALESCE(I.DESCTOTAL,0) +
               COALESCE(I.VRSUBSTICMS, 0) +
               (COALESCE(I.VRIPIACRESCIMO, 0)+COALESCE(I.VRIPI, 0)) +
               COALESCE(I.ACRESCIMO,0))
           ELSE 0.00
        END) AS VRFINANCEIRO,

       CAST(SUM(
        CASE
           WHEN (COALESCE(I.VRBONIFICACAO,0) > 0) AND (T.CONTROLEESTOQUE = 'E') THEN
               (COALESCE(I.VRBONIFICACAO,0)+COALESCE(I.VRIPIACRESCIMO, 0)+COALESCE(I.VRIPI, 0)+COALESCE(I.VRSUBSTICMS, 0)) * (-1)
           WHEN (COALESCE(I.VRBONIFICACAO,0) > 0) AND (T.CONTROLEESTOQUE <> 'E') THEN
               (COALESCE(I.VRBONIFICACAO,0)+COALESCE(I.VRIPIACRESCIMO, 0)+COALESCE(I.VRIPI, 0)+COALESCE(I.VRSUBSTICMS, 0)) 
           ELSE
               0.00
        END) AS NUMERIC(18,2)) AS VRBONIFICACAO,

 
        CAST(SUM(
          CASE
             WHEN (T.CONTROLEESTOQUE = 'E') OR
                  ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                 COALESCE(I.BASEICMSFRETE,0) * (-1)
             WHEN (T.CONTROLEESTOQUE = 'S') OR
                  ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.BASEICMSFRETE,0) 
          ELSE 0.00
        END) AS NUMERIC(18, 2)) AS BASEICMSFRETE,

        CAST(SUM(
        CASE
            WHEN (T.CONTROLEESTOQUE = 'E') THEN
               (COALESCE(I.DESCONTO, 0)+COALESCE(I.DESCTOTAL,0))*(-1)
            WHEN (T.CONTROLEESTOQUE = 'S') THEN
               COALESCE(I.DESCONTO, 0)+COALESCE(I.DESCTOTAL,0)
            WHEN (T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')  THEN
               COALESCE(I.DESCONTO, 0)+COALESCE(I.DESCTOTAL,0)
            WHEN (T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')  THEN
               (COALESCE(I.DESCONTO, 0)+COALESCE(I.DESCTOTAL,0))*(-1)
            ELSE 0
        END) AS NUMERIC(18,2)) AS DESCONTO,

        CAST(SUM(
        CASE
            WHEN (T.CONTROLEESTOQUE = 'E') THEN
               COALESCE(I.ACRESCIMO, 0)*(-1)
            WHEN (T.CONTROLEESTOQUE = 'S') THEN
               COALESCE(I.ACRESCIMO,0)
            WHEN (T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')  THEN
               COALESCE(I.ACRESCIMO,0)
            WHEN (T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')  THEN
               COALESCE(I.ACRESCIMO, 0)*(-1)
            ELSE 0
        END) AS NUMERIC(18,2)) AS ACRESCIMO,


        CAST(SUM(
        CASE
            WHEN (T.CONTROLEESTOQUE = 'E') THEN
               COALESCE(I.icmssubst, 0)*(-1)
            WHEN (T.CONTROLEESTOQUE = 'S') THEN
               COALESCE(I.icmssubst,0)
            WHEN (T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')  THEN
               COALESCE(I.icmssubst,0)
            WHEN (T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')  THEN
               COALESCE(I.icmssubst, 0)*(-1)
            ELSE 0
        END) AS NUMERIC(18,2)) AS VRSUBSTICMS,


        CAST(SUM(
        CASE
            WHEN N.IPI = 'C' THEN
               (COALESCE(I.VRIPIACRESCIMO, 0)+COALESCE(I.VRIPI, 0)) *(-1)
            WHEN N.IPI = 'D' THEN
               COALESCE(I.VRIPIACRESCIMO, 0)+COALESCE(I.VRIPI, 0)
            ELSE 0
        END) AS NUMERIC(18, 2)) AS VRIPI,

        CAST(SUM(
        CASE
            WHEN N.INCIDEICMS = 'D' THEN
               COALESCE(I.VRICMS,0)
            WHEN N.INCIDEICMS = 'C' THEN
               COALESCE(I.VRICMS,0)*(-1)
            ELSE
               0.00
        END) AS NUMERIC(18,4)) AS VRICMS,

        CAST(SUM(
          CASE
             WHEN (T.CONTROLEESTOQUE = 'E') THEN
                 (COALESCE(I.PIS_VRIMPOSTO,0)+COALESCE(I.COFINS_VRIMPOSTO,0))*(-1)
             ELSE
                 (COALESCE(I.PIS_VRIMPOSTO,0)+COALESCE(I.COFINS_VRIMPOSTO,0))
          END ) AS NUMERIC(18,4))  AS VRPISCOFINS,
        
       SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
             (COALESCE(I.CUSTO,0) * COALESCE(I.QTDE,0))*(-1)
           WHEN ((T.CONTROLEESTOQUE = 'S')) OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
             (COALESCE(I.CUSTO,0) * COALESCE(I.QTDE,0))
           ELSE 0
        END ) AS CUSTO,


      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_COMPRA,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_COMPRA,0)
           ELSE 0
        END ) AS CUSTOCOMPRA,

      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_DIFICMS,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_DIFICMS,0)
           ELSE 0
        END ) AS CUSTODIFICMS,


      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_ICMS,0)*(-1))
           WHEN ((T.CONTROLEESTOQUE = 'S')) OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_ICMS,0)
           ELSE 0
        END ) AS CUSTOICMS,

      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_IPI,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_IPI,0)
           ELSE 0
        END ) AS CUSTOIPI,

      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_FRETE,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_FRETE,0)
           ELSE 0
        END ) AS CUSTOFRETE,


      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_SUBST,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_SUBST,0)
           ELSE 0
        END ) AS CUSTOSUBST,

      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_PISCOFINS,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_PISCOFINS,0)
           ELSE 0
        END ) AS CUSTO_PISCOFINS,

      SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'E')) THEN
                (COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_OUTROS,0)*(-1))
           WHEN (T.CONTROLEESTOQUE = 'S') OR
                ((T.CONTROLEESTOQUE = 'N') AND ( N.FINANCEIRO= 'S' ) AND (N.TIPONF = 'S')) THEN
                COALESCE(I.QTDE,0)*COALESCE(I.CUSTO_OUTROS,0)
           ELSE 0
        END ) AS CUSTOOUTROS,

        CAST(AVG( PC.DESPVARIAVEIS ) AS NUMERIC(18,4)) AS DESPVARIAVEIS,

        CAST(SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') THEN
               COALESCE(I.QTDE,0)*(-1)
           WHEN (T.CONTROLEESTOQUE = 'S') THEN
               COALESCE(I.QTDE,0)
           WHEN (T.CONTROLEESTOQUE = 'N') AND (N.TIPONF = 'S') AND (P.TIPOPRODUTO = 2) THEN
               COALESCE(I.QTDE,0)
           ELSE 0
        END) AS NUMERIC(18,4)) AS QTDE_GERAL,

        SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') THEN
               COALESCE(I.PESOBRUTO,0)*COALESCE(I.QTDE,0)*(-1)
           WHEN (T.CONTROLEESTOQUE = 'S') THEN
               COALESCE(I.PESOBRUTO,0)*COALESCE(I.QTDE,0)
           WHEN (T.CONTROLEESTOQUE = 'N') AND (N.TIPONF = 'S') AND (P.TIPOPRODUTO = 2) THEN
               COALESCE(I.PESOBRUTO,0)*COALESCE(I.QTDE,0)
           ELSE 0
        END) AS PESO_GERAL,

        SUM(
        CASE
           WHEN (T.CONTROLEESTOQUE = 'E') THEN
               COALESCE(I.PESOLIQUIDO,0)*COALESCE(I.QTDE,0)*(-1)
           WHEN (T.CONTROLEESTOQUE = 'S') THEN
               COALESCE(I.PESOLIQUIDO,0)*COALESCE(I.QTDE,0)
           WHEN (T.CONTROLEESTOQUE = 'N') AND (N.TIPONF = 'S') AND (P.TIPOPRODUTO = 2) THEN
               COALESCE(I.PESOLIQUIDO,0)*COALESCE(I.QTDE,0)
           ELSE 0
        END) AS PESOLIQ_GERAL,

       0 AS NRMESA,
       C.CUPOMDESCONTOWEB,
       WEBLOJAS_CADSTATUS.NOME_STATUS,
       C.PEDIDOINTERNET,
       C.EMPRESA,
       CONFIG.FANTASIADESCRIPTOGRAFADO,
       C.FPVENDALUCRO,
       C.MARKUP,
       C.FRETECONTA_T AS FRETECONTA,
       C.VRFRETENEGOCIADO,

       (C.VRTOTALPRODUTOS - 
        C.VRDESCONTO - 
        C.VRDESCONTOITEM) AS VRTOTALPRODUTOSLIQ,
       
       CASE
          WHEN (CTAB.FORMACAOPRECO = 'T')
             THEN COALESCE(CTAB.FP_CONSIDERAFRETE, 'F')
             ELSE COALESCE(CONFIG.FP_CONSIDERAFRETE, 'F')
          END
       AS FP_CONSIDERAFRETE

    ,SUM(COALESCE(NOTA.VRNOTA, 0)) AS VRNOTA
    ,COALESCE(C.NRPEDIDOORIGEM,0) AS NRPEDIDOORIGEM
    ,CONFIG.FANTASIADESCRIPTOGRAFADO  AS NOME_EMPRESA
    ,CONFIG.CODIGO AS CODIGO_EMPRESA
    ,STATUSPEDIDO.DESCRICAO AS DESCR_STATUSPEDIDO

FROM CPED C
INNER JOIN IPED I ON C.NRPEDIDO = I.NRPEDIDO
INNER JOIN PRODUTO_CUSTO PC ON PC.PRODUTO = I.CODPROD AND PC.EMPRESA = I.EMPRESA
INNER JOIN NATOPERACAO N ON I.CFOP = N.CODIGO
INNER JOIN CLIFOR ON CLIFOR.CODIGO = C.CLIENTE
INNER JOIN PRODUTO P ON P.CODBARRA = I.CODBARRA
INNER JOIN CONFIG2 ON CONFIG2.FILIAL = C.EMPRESA
LEFT JOIN (SELECT SUM(COALESCE(INF.VRUNITARIO, 0) * COALESCE(INF.QTDE, 1)) AS VRITEM,
                  SUM((COALESCE(INF.VRUNITARIO, 0) * INF.QTDE) -
                       COALESCE(INF.DESCONTO,0) -
                       COALESCE(INF.DESCITEM,0) +
                       COALESCE(INF.BASEICMSFRETE,0) +
                       COALESCE(INF.VRIPIACRESCIMO, 0)+
                       COALESCE(INF.VRIPI, 0)+
                       COALESCE(INF.ACRESCIMO,0)) AS VRNOTA,
                  ITNF.ITEMPEDIDO,
                  ITNF.PEDIDO
            FROM INF
            INNER JOIN ITEMPEDIDONF ITNF ON (ITNF.NRNFCF = INF.NRNFCF AND
                                             ITNF.SERIE = INF.SERIE AND
                                             ITNF.ITEMNF = INF.NRITEM)
            GROUP BY ITNF.PEDIDO, ITNF.ITEMPEDIDO
          ) AS NOTA ON NOTA.PEDIDO = I.NRPEDIDO AND NOTA.ITEMPEDIDO = I.ITEM
LEFT OUTER JOIN FUNCIONARIO F ON I.VENDEDOR = F.FUNCIONARIO
LEFT OUTER JOIN FUNCIONARIO IND ON I.INDICACAO = IND.FUNCIONARIO
LEFT OUTER JOIN RAMOATIV ON CLIFOR.RAMO = RAMOATIV.RAMOATIVIDADE
LEFT OUTER JOIN CONVENIO ON CLIFOR.CONVENIO = CONVENIO.CONVENIO
LEFT OUTER JOIN CLIGRUPO ON CLIGRUPO.GRUPO = CLIFOR.GRUPOCLIENTE
LEFT OUTER JOIN ATENDIMENTO ATEND ON ATEND.ATENDIMENTO = C.ATENDIMENTO
LEFT OUTER JOIN TIPOPEDIDO T ON T.TIPO = C.TIPO
LEFT OUTER JOIN TRANSPORTADORA TP1 ON TP1.CODIGO = C.TRANSPORTADORA
LEFT OUTER JOIN TRANSPORTADORA TP2 ON TP2.CODIGO = C.REDESPACHO
LEFT OUTER JOIN WEBLOJAS_CADSTATUS ON  WEBLOJAS_CADSTATUS.COD_CADSTATUS = C.STATUSWEB AND WEBLOJAS_CADSTATUS.TIPO = C.TIPO
--LEFT OUTER JOIN cte_condpagto ON cte_condpagto.PEDIDO = C.NRPEDIDO
LEFT OUTER JOIN CONFIG ON CONFIG.CODIGO = C.EMPRESA
LEFT OUTER JOIN CTAB ON CTAB.CODIGO = C.TABPRECO
LEFT OUTER JOIN STATUSPEDIDO ON STATUSPEDIDO.CODIGO = C.STATUSPEDIDO
LEFT JOIN GRUPO2 ON GRUPO2.CODIGO = (CASE WHEN COALESCE(I.GRUPO2,0) > 0 THEN
                                    I.GRUPO2 ELSE
                                    P.GRUPO2 END)
LEFT JOIN GRUPO3 ON GRUPO3.CODIGO = (CASE WHEN COALESCE(I.GRUPO3,0) > 0 THEN
                                    I.GRUPO3 ELSE
                                    P.GRUPO3 END)
WHERE  C.EMPRESA IS NOT NULL  AND C.TIPO <> 'Z' 
AND C.DTPEDIDO >= '01-Jan-2021' 
--AND C.DTPEDIDO <= CURRENT_DATE
--AND C.NRPEDIDO = 88
GROUP BY
        C.NRPEDIDO,
        C.NRPEDIDOORIGEM,
        C.DTPEDIDO,       
        I.CFOP,
        C.CLIENTE,
        C.RAZSOCIAL,
        PAISFAT,
        CASE WHEN COALESCE(C.CIDADEFAT, '') <> '' THEN C.CIDADEFAT
        ELSE CLIFOR.CIDADEFAT END,
        CASE WHEN COALESCE(C.UFFAT, '') <> '' THEN C.UFFAT
        ELSE CLIFOR.UFFAT END,
        CLIFOR.DTCAD,
        C.VENDEDOR,
        C.TRANSPORTADORA,
        C.MOTIVOBLOQ,
        C.USUARIOLIBERACAO,
        T.CONTROLEESTOQUE,
        I.ALIQICMS,
        N.NATUREZA,
        ATEND.DESCRICAO, 
        F.NOME,
        IND.NOME,
        CLIFOR.CONVENIO_FUNC,
        T.DESCRICAO,
        CASE
           WHEN (CONFIG2.UTILIZACONTROLEENTREGA <> 'T') THEN
              C.DTFATURA
        END, 
        I.TRIBUTACAO,
        I.VRFRETE,
        C.CUPOMDESCONTOWEB,
        WEBLOJAS_CADSTATUS.NOME_STATUS,
        C.PEDIDOINTERNET,
        C.EMPRESA,
        C.FPVENDALUCRO,
        C.MARKUP,
        C.FRETECONTA_T,
        C.VRFRETENEGOCIADO,

        (C.VRTOTALPRODUTOS - 
         C.VRDESCONTO - 
         C.VRDESCONTOITEM),

        CASE
           WHEN (CTAB.FORMACAOPRECO = 'T')
              THEN COALESCE(CTAB.FP_CONSIDERAFRETE, 'F')
              ELSE COALESCE(CONFIG.FP_CONSIDERAFRETE, 'F')
        END
    ,CONFIG.FANTASIADESCRIPTOGRAFADO 
    ,CONFIG.CODIGO
    ,STATUSPEDIDO.DESCRICAO
    --,DTPAGTO
    --,FORMA_PAGAMENTO
    --,PARCELA_CPP
    ORDER BY C.DTPEDIDO, C.NRPEDIDO