WITH CONDICAO_PAGAMENTO AS (
SELECT DISTINCT
	
	CONDPAGTOOS.NROS,
	CONDPAGTOOS.NRPAGTOS PARCELA,
	
	CASE
	    WHEN CONDPAGTOOS.TIPO = 0 THEN
	       '0-DINHEIRO'
	    WHEN CONDPAGTOOS.TIPO = 1 THEN
	       '1-CHEQUE'
	    WHEN CONDPAGTOOS.TIPO = 2 THEN
	       '2-CARTAO'
	    WHEN CONDPAGTOOS.TIPO = 3 THEN
	       '3-VALE'
	    WHEN CONDPAGTOOS.TIPO = 4 THEN
	       '4-CARTEIRA'
	    WHEN CONDPAGTOOS.TIPO = 5 THEN
	       '5-CR CLIENTE'
	    WHEN CONDPAGTOOS.TIPO = 6 THEN
	       '6-FINANCEIRA'
	    WHEN CONDPAGTOOS.TIPO = 10 THEN
	       '10-DEPOSITO'
	END AS TIPO,
	
	CONDPAGTOOS.VENCTO,
	CONDPAGTOOS.VALOR,
	COALESCE(CARTAO.OPERADORA, 'SEM OPERADORA') OPERADORA

	FROM CONDPAGTOOS

LEFT JOIN CARTAO ON CARTAO.CODIGO = CONDPAGTOOS.OPERADORA ) 

SELECT * FROM CONDICAO_PAGAMENTO
WHERE VENCTO >= '01.01.2021'
ORDER BY 1, 2