WITH BASE_PRODUTO AS (
SELECT DISTINCT
	'PRODUTO' TIPO,
	IOS.NROS,
	IOS.NRITEM COD,
	PRODUTO.DESCRICAO,
	IOS.QTDE,
	COALESCE(IOS.VRUNITARIO, 0) VALOR,
	COALESCE(IOS.DESCONTO, 0) VRDESCONTO,
	(COALESCE(IOS.VRUNITARIO, 0) - COALESCE(IOS.DESCONTO, 0)) VRTOTAL
	
FROM IOS

LEFT JOIN PRODUTO ON PRODUTO.CODPROD = IOS.CODPROD)

, BASE_SERVICO AS (SELECT

	'SERVIÇO' TIPO,
	HOS.NROS,
	HOS.SERVICO COD,
	HOS.DESCRSERV DESCRICAO,
	HOS.QTDE,
	COALESCE(HOS.VRSERVICO, 0) VALOR,
	COALESCE(HOS.VRDESCONTO, 0) VRDESCONTO,
	(COALESCE(HOS.VRSERVICO, 0) - COALESCE(HOS.VRDESCONTO, 0)) VRTOTAL
	
FROM HOS )

, BASE_FINAL AS (
SELECT * FROM BASE_PRODUTO 
UNION ALL 
SELECT * FROM BASE_SERVICO) 
	SELECT * FROM BASE_FINAL
	ORDER BY 2, 3