WITH ORDEM_SERVICO AS (SELECT DISTINCT
	CONFIG.FANTASIADESCRIPTOGRAFADO EMPRESA, 
	COALESCE(C.NRNFCF, '000000000') NRNOTA,
	C.NROS NROS,
	COALESCE(FUNC.NOME, 'SEM ATENDENTE') ATENDENTE,
	S.DESCRSITUACAOOS SITUACAO,
	C.DTCHAMADA DTABERTURA,
	COALESCE(ATE.DESCRICAO, 'SEM ATENDIMENTO') ATENDIMENTO,
	COALESCE(ES.DESCRICAO, 'SEM STATUS') STATUS_EQUIPAMENTO,
	C.USUARIO,
	C.HORAABERTURA HORAABERTURA,
	TOS.DESCRTIPOOS TIPOOS,
	C.DATAFECHAMENTO DATAFECHAMENTO,
	C.HORAFECHAMENTO HORAFECHAMENTO,
	C.RAZSOCIAL CLIENTE,
	C.CIDADEFAT CIDADE,
    C.BAIRROFAT BAIRRO,
	C.UFFAT UF, 
	C.DTCHAMADA DATAENTRADA,
	C.HORAABERTURA HORAENTRADA,
    CAST(C.DTPROMETIDA + C.HORAPROMETIDA AS TIMESTAMP) AS DATAPROMETIDA,
    CAST(C.DATAVISITAINICIAL + C.HORAVISITAINICIAL AS TIMESTAMP) DATAHORA_VISITAINICIAL,
    CAST(C.DATAVISITAFINAL + C.HORAVISITAFINAL AS TIMESTAMP) DATAHORA_VISITAFINAL,
	C.DATAVISITAINICIAL,
	C.HORAVISITAINICIAL,
	C.DATAVISITAFINAL,
	C.HORAVISITAFINAL,
	C.DEFEITORECLAMADO DEFEITO,
	C.SOLUCAO,
	COALESCE(C.VRSERVICO, 0) VALOR_SERVICOS,
	COALESCE(C.VRPECAS, 0) VALOR_PRODUTOS,
	(COALESCE(C.VRDESCITEM , 0) + COALESCE(C.VRDESCSERVICO , 0)) VALOR_DESCONTO,
	(COALESCE(C.VRSERVICO, 0) + COALESCE(C.VRPECAS, 0)- (COALESCE(C.VRDESCITEM , 0) + COALESCE(C.VRDESCSERVICO , 0))) VALOR_TOTAL,
	COALESCE(MONTADOR.NOME, 'SEM MONTADOR') MONTADOR, 
	COALESCE(EQUIPAMENTO.NUMEROSERIE, 'SEM NR. SÉRIE') NRSERIE,
	COALESCE(EQUIPAMENTO.DESCREQUIPAMENTO, 'SEM EQUIPAMENTO') EQUIPAMENTO
	
FROM COS C

LEFT JOIN CONFIG ON CONFIG.CODIGO = C.EMPRESA 
LEFT JOIN SITUACAOOS S ON S.SITUACAOOS = C.SITUACAO
LEFT JOIN TIPOOS TOS ON TOS.TIPOOS = C.TIPO 
LEFT JOIN FUNCIONARIO FUNC ON FUNC.FUNCIONARIO = C.ATENDENTE
LEFT JOIN FUNCIONARIO MONTADOR ON MONTADOR.FUNCIONARIO = C.MONTADOR
LEFT JOIN ATENDIMENTO ATE ON ATE.ATENDIMENTO = C.ATENDIMENTO
LEFT JOIN EQUIP_STATUS ES ON ES.CODIGO = C.STATUS
LEFT JOIN EQUIPAMENTO ON EQUIPAMENTO.NUMEROSERIE = C.PLACA
LEFT JOIN CLIFOR CLI ON CLI.CODIGO = C.CLIENTE

WHERE 1=1 
AND C.DTCHAMADA >= '01.01.2021'

) SELECT * FROM ORDEM_SERVICO
	ORDER BY NROS, DTABERTURA